Print commands before we run them + terminal colors for output
NixOS/cabal2nix pull request #636
Opened 2024-12-12 23:57 UTC by 9999years

This adds terminal colors to `cabal2nix`'s output. This checks if `stderr` `isatty` so that output will not be colored if (for example) `cabal2nix`'s `stderr` is being piped to a file. It also respects the `$NO_COLOR` and `$FORCE_COLOR` environment variables for toggling the output coloring (see [no-color.org](https://no-color.org/)).

A couple small changes while I was preparing this:

1. I added `nix-prefetch-scripts` to the `shell.nix` so that you can run `cabal2nix` successfully while hacking on it.
2. I added a line to print the fetcher command (like `nix-prefetch-git ...`) before we run it. This makes it a lot clearer where the errors come from, and which errors are being ignored (because we're trying another fetcher).

2024-12-14 21:13 UTC, sternenseemann commented
Good idea, I think this is a good migitation for the error message problem the current fetcher logic has!

Not quite sure what to think about colored output, i.e. if the extra code is worth it…

2024-12-16 17:39 UTC, 9999years commented
@sternenseemann Happy to remove the colored output if you'd prefer (or you can update my branch -- just drop the last commit), let me know

2024-12-16 22:18 UTC, sternenseemann commented
I've merged those changes manually, we can leave this PR for the color changes. I'm going to keep thinking about it. Maybe @maralorn and @cdepillabout want to comment?

2024-12-17 01:13 UTC, cdepillabout commented
I think I'm generally in favor of (optional) colors.

For CLI programs that use color, I think I'd also expect a `--color` / `--no-color` CLI flag to exist, but I don't think not having it should necessarily think that should block this PR.

@9999years could you post a screenshot of what the colors look like in the output of cabal2nix?

2024-12-17 17:30 UTC, 9999years commented
@cdepillabout Added a screenshot to the PR description!

2024-12-18 00:14 UTC, cdepillabout commented
I think the colors seems nice, and it will likely make visually parsing the output of `cabal2nix` easier.  I'm for merging this.

2024-12-24 14:58 UTC, maralorn commented
Unsurprisingly I am all in favor of colorful output. Code complexity seems manageable.

2025-02-06 15:18 UTC, sternenseemann commented
Alright. Would be good if someone could review and merge this PR soon-ish, I think releasing a new cabal2nix version is sort of overdue (and we should get out a fix for text >= 2.1.2 rather sooner than later).

2025-03-06 00:02 UTC, 9999years commented
Anything needed for this?

2025-03-09 11:49 UTC, maralorn requested changes
This is great actually! We should ship it.

I am just confused about one spot. Let’s clarify that.

2025-03-09 11:49 UTC, maralorn commented on cabal2nix/src/Distribution/Nixpkgs/Fetch.hs
> +    colorStderrLn warningColor "** need a revision for VCS when the hash is given. skipping."
The dropped mzero seems like a semantic change to me. Is that intentional?

2025-03-10 17:03 UTC, 9999years commented on cabal2nix/src/Distribution/Nixpkgs/Fetch.hs
> +    colorStderrLn warningColor "** need a revision for VCS when the hash is given. skipping."
Ooh, good catch. I didn't realize it was being used as an early-return here.

2025-03-10 17:39 UTC, maralorn approved these changes

2025-03-10 17:39 UTC, merged